In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("services.csv")

In [3]:
df.head()

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN

In [4]:
df.head(3)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN

In [5]:
df.tail()

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [6]:
df.tail(2)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [7]:
type (df)

pandas.core.frame.DataFrame

In [8]:
list(df.columns)

['id',
 'location_id',
 'program_id',
 'accepted_payments',
 'alternate_name',
 'application_process',
 'audience',
 'description',
 'eligibility',
 'email',
 'fees',
 'funding_sources',
 'interpretation_services',
 'keywords',
 'languages',
 'name',
 'required_documents',
 'service_areas',
 'status',
 'wait_time',
 'website',
 'taxonomy_ids']

In [9]:
df["status"]

0       active
1       active
2       active
3       active
4       active
5       active
6       active
7       active
8       active
9       active
10      active
11      active
12      active
13      active
14      active
15      active
16      active
17      active
18      active
19     defunct
20    inactive
21      active
22      active
Name: status, dtype: object

In [10]:
type(df["status"])

pandas.core.series.Series

In [11]:
type(df[["status",'required_documents']])

pandas.core.frame.DataFrame

In [12]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [13]:
df.info

<bound method DataFrame.info of     id  location_id  program_id         accepted_payments  \
0    1            1         NaN                       NaN
1    2            2         NaN                       NaN
2    3            3         NaN                       NaN
3    4            4         NaN                       NaN
4    5            5         NaN                       NaN
5    6            6         NaN                       NaN
6    7            7         NaN                       NaN
7    8            8         NaN                       NaN
8    9            9         NaN                       NaN
9   10           10         NaN                       NaN
10  11           11         NaN                       NaN
11  12           12         NaN                       NaN
12  13           13         NaN                       NaN
13  14           14         NaN                       NaN
14  15           15         NaN                       NaN
15  16           16         NaN                       NaN
16  17           17         NaN                       NaN
17  18           18         NaN                       NaN
18  19           19         NaN                       NaN
19  20           20         NaN                       NaN
20  21           21         NaN                       NaN
21  22           22         NaN  Cash, Check, Credit Card
22  23           22         NaN                       NaN

           alternate_name                                application_process  \
0                     NaN                         Walk in or apply by phone.
1                     NaN                 Apply by phone for an appointment.
2                     NaN        Phone for information (403-4300 Ext. 4322).
3                     NaN                                    Apply by phone.
4                     NaN                             Phone for information.
5                     NaN  Walk in or apply by phone for membership appli...
6                     NaN  Apply by phone or be referred by a doctor, soc...
7                     NaN                                    Apply by phone.
8                     NaN  Walk in. Proof of residency in California requ...
9                     NaN  Walk in. Proof of California residency to rece...
10                    NaN  Walk in. Proof of California residency require...
11                    NaN  Walk in or apply by phone, email or webpage re...
12                    NaN  Walk in. Proof of California residency require...
13                    NaN  Call for appointment. Referral from human serv...
14                    NaN          Walk in or through other agency referral.
15                    NaN  Walk in. Written application, identification r...
16                    NaN                              Call for information.
17                    NaN  Call for screening appointment. Medical visits...
18                    NaN     Call for screening appointment (650-347-3648).
19                    NaN                                           Walk in.
20                    NaN                    By phone during business hours.
21  Fotos para pasaportes                  Walk in or apply by phone or mail
22                    NaN                  Walk in or apply by phone or mail

                                             audience  \
0   Older adults age 55 or over, ethnic minorities...
1        Residents of San Mateo County age 55 or over
2   Older adults age 55 or over who can benefit fr...
3   Parents, children, families with problems of c...
4   Low-income working families with children tran...
5                                             Any age
6   Older adults who have memory or sensory loss, ...
7   Senior citizens age 60 or over, disabled indiv...
8      Ethnic minorities, especially Spanish speaking
9                                                 NaN
10                                                NaN
11  Adults, parents, children in 1st-12th grades i...
12                                                NaN
13  Individuals or families with low or no income ...
14  Adult alcoholic/drug addictive men and women w...
15                                                NaN
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN
20                                                NaN
21  Profit and nonprofit businesses, the public, m...
22  Second service and nonprofit businesses, the p...

                                          description  \
0   A walk-in center for older adults that provide...
1   Provides training and job placement to eligibl...
2   Offers supportive counseling services to San M...
3   Provides supervised visitation services and a ...
4   Provides fixed 8% short term loans to eligible...
5   A multipurpose center offering a wide variety ...
6   Rosener House is a day center for older adults...
7   Delivers a hot meal to the home of persons age...
8   Provides general reading material, including b...
9   Provides general reading and media materials, ...
10  Provides general reading materials, including ...
11  Offers an intergenerational literacy program f...
12  Provides general reading materials, including ...
13  Provides food, clothing, bus tokens and shelte...
14  Provides a long-term (6-12 month) residential ...
15  Provides emergency assistance including food a...
16  Provides emergency food, clothing and furnitur...
17  By appointment only, Project Smile provides a ...
18  Provides free medical and dental care to those...
19              no unrequired fields for this service
20                                just a test service
21  [NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...
22  [NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...

                                          eligibility                  email  \
0   Age 55 or over for most programs, age 60 or ov...                    NaN
1   Age 55 or over, county resident and willing an...                    NaN
2         Resident of San Mateo County age 55 or over                    NaN
3                                                 NaN                    NaN
4   Eligibility: Low-income family with legal cust...                    NaN
5                                                 NaN                    NaN
6                                      Age 18 or over                    NaN
7             Homebound person unable to cook or shop                    NaN
8     Resident of California to obtain a library card                    NaN
9             Resident of California to obtain a card                    NaN
10  Resident of California to obtain a library car...                    NaN
11  English-speaking adult reading at or below 7th...                    NaN
12    Resident of California to obtain a library card                    NaN
13  None for most services. For emergency assistan...                    NaN
14  Age 21-60, detoxed, physically able and willin...                    NaN
15                      None for emergency assistance                    NaN
16                                Low-income families                    NaN
17    Low-income person without access to health care                    NaN
18    Low-income person without access to health care                    NaN
19                                                NaN                    NaN
20                                                NaN                    NaN
21                                                NaN  passports@example.org
22                                                NaN                    NaN

    ...                            interpretation_services  \
0   ...                                                NaN
1   ...                                                NaN
2   ...                                                NaN
3   ...                                                NaN
4   ...                                                NaN
5   ...                                                NaN
6   ...                                                NaN
7   ...                                                NaN
8   ...                                                NaN
9   ...                                                NaN
10  ...                                                NaN
11  ...                                                NaN
12  ...                                                NaN
13  ...                                                NaN
14  ...                                                NaN
15  ...                                                NaN
16  ...                                                NaN
17  ...                                                NaN
18  ...                                                NaN
19  ...                                                NaN
20  ...                                                NaN
21  ...  We offer 3-way interpretation services over th...
22  ...                                                NaN

                                             keywords languages  \
0   ADULT PROTECTION AND CARE SERVICES, Meal Sites...       NaN
1   EMPLOYMENT/TRAINING SERVICES, Job Development,...       NaN
2   Geriatric Counseling, Older Adults, Gay, Lesbi...       NaN
3   INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...       NaN
4      COMMUNITY SERVICES, Speakers, Automobile Loans       NaN
5   ADULT PROTECTION AND CARE SERVICES, In-Home Su...       NaN
6   ADULT PROTECTION AND CARE SERVICES, Adult Day ...       NaN
7   ADULT PROTECTION AND CARE SERVICES, Meal Sites...       NaN
8   EDUCATION SERVICES, Library, Libraries, Public...       NaN
9   EDUCATION SERVICES, Library, Libraries, Public...       NaN
10  EDUCATION SERVICES, Library, Libraries, Public...       NaN
11  EDUCATION SERVICES, Adult, Alternative, Litera...       NaN
12  EDUCATION SERVICES, Library, Libraries, Public...       NaN
13  COMMUNITY SERVICES, Interpretation/Translation...       NaN
14  ALCOHOLISM SERVICES, Residential Care, DRUG AB...       NaN
15  COMMODITY SERVICES, Clothing/Personal Items, C...       NaN
16  COMMODITY SERVICES, Clothing/Personal Items, C...       NaN
17  HEALTH SERVICES, Outpatient Care, Community Cl...       NaN
18  HEALTH SERVICES, Outpatient Care, Community Cl...       NaN
19                                                NaN       NaN
20                                                NaN       NaN
21                                    Salud, Medicina   Spanish
22         Ruby on Rails/Postgres/Redis, testing, wic       NaN

                                    name  \
0        Fair Oaks Adult Activity Center
1       Second Career Employment Program
2                 Senior Peer Counseling
3               Family Visitation Center
4      Economic Self-Sufficiency Program
5   Little House Recreational Activities
6       Rosener House Adult Day Services
7         Meals on Wheels - South County
8                       Fair Oaks Branch
9                           Main Library
10                       Schaberg Branch
11                          Project Read
12                 Redwood Shores Branch
13                    Redwood City Corps
14           Adult Rehabilitation Center
15                       Sunnyvale Corps
16     South San Francisco Citadel Corps
17                         Project Smile
18         San Mateo Free Medical Clinic
19             Service with blank fields
20       Service for Admin Test Location
21                       Passport Photos
22                  Example Service Name

                          required_documents  \
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN
5                                        NaN
6                                        NaN
7                                        NaN
8                                        NaN
9                                        NaN
10                                       NaN
11                                       NaN
12                                       NaN
13                                       NaN
14                                       NaN
15                                       NaN
16                                       NaN
17                                       NaN
18                                       NaN
19                                       NaN
20                                       NaN
21  Government-issued picture identification
22                                       NaN

                            service_areas    status  \
0                                   Colma    active
1                        San Mateo County    active
2                        San Mateo County    active
3                        San Mateo County    active
4                        San Mateo County    active
5                        San Mateo County    active
6     Belmont, Burlingame, East Palo Alto    active
7                 Belmont, East Palo Alto    active
8                        San Mateo County    active
9                        San Mateo County    active
10                       San Mateo County    active
11                              Daly City    active
12                       San Mateo County    active
13    Belmont, Burlingame, East Palo Alto    active
14       Alameda County, San Mateo County    active
15                                    NaN    active
16  Colma, Daly City, South San Francisco    active
17                         East Palo Alto    active
18                    Belmont, Burlingame    active
19                                    NaN   defunct
20                       San Mateo County  inactive
21       Alameda County, San Mateo County    active
22       San Mateo County, Alameda County    active

                                            wait_time                 website  \
0                                            No wait.                     NaN
1                                             Varies.                     NaN
2                                             Varies.                     NaN
3                                            No wait.                     NaN
4                                                 NaN                     NaN
5                                            No wait.                     NaN
6                                            No wait.                     NaN
7                                            No wait.                     NaN
8                                            No wait.                     NaN
9                                            No wait.                     NaN
10                                           No wait.                     NaN
11  Depends on availability of tutors for small gr...                     NaN
12                                           No wait.                     NaN
13                                  Up to 20 minutes.                     NaN
14  Varies according to available beds for men and...                     NaN
15                                           No wait.                     NaN
16                                                NaN                     NaN
17                                            Varies.                     NaN
18                                            Varies.                     NaN
19                                                NaN                     NaN
20                                                NaN                     NaN
21                                No wait to 2 weeks.  http://www.example.com
22                                 No wait to 2 weeks  http://www.example.com

                                taxonomy_ids
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN
5                                        NaN
6                                        NaN
7                                        NaN
8                                        NaN
9                                        NaN
10                                       NaN
11                                       NaN
12                                       NaN
13                                       NaN
14                                       NaN
15                                       NaN
16                                       NaN
17                                       NaN
18                                       NaN
19                                       NaN
20                                       NaN
21  105, 108, 108-05, 108-05-01, 111, 111-05
22                                       NaN

[23 rows x 22 columns]>

In [14]:
# xl files:-

In [15]:
pip install lxml

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lxml in c:\users\adhinath\appdata\roaming\python\python38\site-packages (4.9.3)
Note: you may need to restart the kernel to use updated packages.

In [16]:
import lxml

In [17]:
import pandas as pd

In [18]:
pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\adhinath\appdata\roaming\python\python38\site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in c:\users\adhinath\appdata\roaming\python\python38\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [19]:
df1 = pd.read_excel("LUSID Excel - Setting up your market data.xlsx")

In [20]:
df1.head

<bound method NDFrame.head of     Unnamed: 0  Unnamed: 1  Unnamed: 2  \
0          NaN         NaN         NaN
1          NaN         NaN         NaN
2          NaN         NaN         NaN
3          NaN         NaN         NaN
4          NaN         NaN         NaN
5          NaN         NaN         NaN
6          NaN         NaN         NaN
7          NaN         NaN         NaN
8          NaN         NaN         NaN
9          NaN         NaN         NaN
10         NaN         NaN         NaN
11         NaN         NaN         NaN
12         NaN         NaN         NaN
13         NaN         NaN         NaN
14         NaN         NaN         NaN
15         NaN         NaN         NaN
16         NaN         NaN         NaN
17         NaN         NaN         NaN
18         NaN         NaN         NaN
19         NaN         NaN         NaN
20         NaN         NaN         NaN
21         NaN         NaN         NaN
22         NaN         NaN         NaN
23         NaN         NaN         NaN
24         NaN         NaN         NaN
25         NaN         NaN         NaN
26         NaN         NaN         NaN
27         NaN         NaN         NaN

                                           Unnamed: 3  \
0                                                 NaN
1                                  Datetimes in LUSID
2                                                 NaN
3    This sheet allows you to format datetimes for...
4         If you have any questions please visit our:
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN
20                                                NaN
21                                                NaN
22                                                NaN
23                                                NaN
24                                                NaN
25                                                NaN
26                                                NaN
27                                                NaN

                                           Unnamed: 4  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                           Getting Started tutorials
6                             Knowledge Base articles
7                                       or Contact us
8                                                 NaN
9                                                 NaN
10                                                NaN
11  LUSID accepts datetimes in any recognised Exce...
12                                                NaN
13                     Excel formats to show datetime
14                                                NaN
15                          Enter the date to convert
16                                                NaN
17                    This date has no time component
18                                                NaN
19                             Specify time component
20                                                NaN
21  Add to your date and display the complete date...
22                                                NaN
23   Although the date can still appears without time
24                                                NaN
25                       Add an hour to your datetime
26                                                NaN
27               Subtract a minute from your datetime

                    Unnamed: 5  Unnamed: 6  \
0                          NaN         NaN
1                          NaN         NaN
2                          NaN         NaN
3                          NaN         NaN
4                          NaN         NaN
5                          NaN         NaN
6                          NaN         NaN
7                          NaN         NaN
8                          NaN         NaN
9                          NaN         NaN
10                         NaN         NaN
11                         NaN         NaN
12                         NaN         NaN
13                         NaN         NaN
14                         NaN         NaN
15         2019-04-10 00:00:00         NaN
16                         NaN         NaN
17         2019-04-10 00:00:00         NaN
18                         NaN         NaN
19             13:30:45.550000         NaN
20                         NaN         NaN
21  2019-04-10 13:30:45.550000         NaN
22                         NaN         NaN
23  2019-04-10 13:30:45.550000         NaN
24                         NaN         NaN
25  2019-04-10 14:30:45.550000         NaN
26                         NaN         NaN
27  2019-04-10 14:29:45.550000         NaN

                                           Unnamed: 7  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11  LUSID also accepts UTC, UTS offsets and cutlabels
12                                                NaN
13                                 Additional formats
14                                                NaN
15                            Standard UTC timestamp:
16                                                NaN
17                         Convert date into a string
18                                                NaN
19       UTC offset (not recognised as an excel date)
20                                                NaN
21                                           Cutlabel
22                                                NaN
23                                                NaN
24                                                NaN
25                                                NaN
26                                                NaN
27                                                NaN

                   Unnamed: 8  \
0                         NaN
1                         NaN
2                         NaN
3                         NaN
4                         NaN
5                         NaN
6                         NaN
7                         NaN
8                         NaN
9                         NaN
10                        NaN
11                        NaN
12                        NaN
13                        NaN
14                        NaN
15  "YYYY-MM-DDTHH:MM:SS.00Z"
16                        NaN
17   2019-04-10T 13:30:45.55Z
18                        NaN
19  2019-04-10T13:30:45+04:00
20                        NaN
21  2019-04-10NSingaporeClose
22                        NaN
23                        NaN
24                        NaN
25                        NaN
26                        NaN
27                        NaN

                                           Unnamed: 9
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15  Where Z indicates Zulu time (UTC+0), and is eq...
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN
20                                                NaN
21                                                NaN
22                                                NaN
23                                                NaN
24                                                NaN
25                                                NaN
26                                                NaN
27                                                NaN  >

In [21]:
df1.head(2)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Datetimes in LUSID,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df1.tail

<bound method NDFrame.tail of     Unnamed: 0  Unnamed: 1  Unnamed: 2  \
0          NaN         NaN         NaN
1          NaN         NaN         NaN
2          NaN         NaN         NaN
3          NaN         NaN         NaN
4          NaN         NaN         NaN
5          NaN         NaN         NaN
6          NaN         NaN         NaN
7          NaN         NaN         NaN
8          NaN         NaN         NaN
9          NaN         NaN         NaN
10         NaN         NaN         NaN
11         NaN         NaN         NaN
12         NaN         NaN         NaN
13         NaN         NaN         NaN
14         NaN         NaN         NaN
15         NaN         NaN         NaN
16         NaN         NaN         NaN
17         NaN         NaN         NaN
18         NaN         NaN         NaN
19         NaN         NaN         NaN
20         NaN         NaN         NaN
21         NaN         NaN         NaN
22         NaN         NaN         NaN
23         NaN         NaN         NaN
24         NaN         NaN         NaN
25         NaN         NaN         NaN
26         NaN         NaN         NaN
27         NaN         NaN         NaN

                                           Unnamed: 3  \
0                                                 NaN
1                                  Datetimes in LUSID
2                                                 NaN
3    This sheet allows you to format datetimes for...
4         If you have any questions please visit our:
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN
20                                                NaN
21                                                NaN
22                                                NaN
23                                                NaN
24                                                NaN
25                                                NaN
26                                                NaN
27                                                NaN

                                           Unnamed: 4  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                           Getting Started tutorials
6                             Knowledge Base articles
7                                       or Contact us
8                                                 NaN
9                                                 NaN
10                                                NaN
11  LUSID accepts datetimes in any recognised Exce...
12                                                NaN
13                     Excel formats to show datetime
14                                                NaN
15                          Enter the date to convert
16                                                NaN
17                    This date has no time component
18                                                NaN
19                             Specify time component
20                                                NaN
21  Add to your date and display the complete date...
22                                                NaN
23   Although the date can still appears without time
24                                                NaN
25                       Add an hour to your datetime
26                                                NaN
27               Subtract a minute from your datetime

                    Unnamed: 5  Unnamed: 6  \
0                          NaN         NaN
1                          NaN         NaN
2                          NaN         NaN
3                          NaN         NaN
4                          NaN         NaN
5                          NaN         NaN
6                          NaN         NaN
7                          NaN         NaN
8                          NaN         NaN
9                          NaN         NaN
10                         NaN         NaN
11                         NaN         NaN
12                         NaN         NaN
13                         NaN         NaN
14                         NaN         NaN
15         2019-04-10 00:00:00         NaN
16                         NaN         NaN
17         2019-04-10 00:00:00         NaN
18                         NaN         NaN
19             13:30:45.550000         NaN
20                         NaN         NaN
21  2019-04-10 13:30:45.550000         NaN
22                         NaN         NaN
23  2019-04-10 13:30:45.550000         NaN
24                         NaN         NaN
25  2019-04-10 14:30:45.550000         NaN
26                         NaN         NaN
27  2019-04-10 14:29:45.550000         NaN

                                           Unnamed: 7  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11  LUSID also accepts UTC, UTS offsets and cutlabels
12                                                NaN
13                                 Additional formats
14                                                NaN
15                            Standard UTC timestamp:
16                                                NaN
17                         Convert date into a string
18                                                NaN
19       UTC offset (not recognised as an excel date)
20                                                NaN
21                                           Cutlabel
22                                                NaN
23                                                NaN
24                                                NaN
25                                                NaN
26                                                NaN
27                                                NaN

                   Unnamed: 8  \
0                         NaN
1                         NaN
2                         NaN
3                         NaN
4                         NaN
5                         NaN
6                         NaN
7                         NaN
8                         NaN
9                         NaN
10                        NaN
11                        NaN
12                        NaN
13                        NaN
14                        NaN
15  "YYYY-MM-DDTHH:MM:SS.00Z"
16                        NaN
17   2019-04-10T 13:30:45.55Z
18                        NaN
19  2019-04-10T13:30:45+04:00
20                        NaN
21  2019-04-10NSingaporeClose
22                        NaN
23                        NaN
24                        NaN
25                        NaN
26                        NaN
27                        NaN

                                           Unnamed: 9
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15  Where Z indicates Zulu time (UTC+0), and is eq...
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN
20                                                NaN
21                                                NaN
22                                                NaN
23                                                NaN
24                                                NaN
25                                                NaN
26                                                NaN
27                                                NaN  >

In [23]:
df1.tail(3)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
25,NaN,NaN,NaN,NaN,Add an hour to your datetime,2019-04-10 14:30:45.550000,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,Subtract a minute from your datetime,2019-04-10 14:29:45.550000,NaN,NaN,NaN,NaN

In [24]:
type(df1)

pandas.core.frame.DataFrame

In [25]:
df1.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],
      dtype='object')

In [26]:
df1['Unnamed: 7']

0                                                   NaN
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                                                   NaN
5                                                   NaN
6                                                   NaN
7                                                   NaN
8                                                   NaN
9                                                   NaN
10                                                  NaN
11    LUSID also accepts UTC, UTS offsets and cutlabels
12                                                  NaN
13                                   Additional formats
14                                                  NaN
15                              Standard UTC timestamp:
16                                                  NaN
17                           Convert date into a string
18                                                  NaN
19         UTC offset (not recognised as an excel date)
20                                                  NaN
21                                             Cutlabel
22                                                  NaN
23                                                  NaN
24                                                  NaN
25                                                  NaN
26                                                  NaN
27                                                  NaN
Name: Unnamed: 7, dtype: object

In [27]:
type(df1['Unnamed: 7'])

pandas.core.series.Series

In [28]:
type(df1[['Unnamed: 7']])

pandas.core.frame.DataFrame

In [29]:
df2= pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

KeyboardInterrupt:

In [ ]:
import pandas as pd

In [ ]:
df